# Generated by Django 6.0.7 on 2026-07-23 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload_hours', models.PositiveIntegerField()),
                ('sleep_hours', models.PositiveIntegerField()),
                ('sleep_quality', models.CharField(max_length=50)),
                ('study_habit_score', models.PositiveIntegerField()),
                ('social_media_hours', models.PositiveIntegerField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_level', models.CharField(max_length=20)),
                ('factors', models.TextField(default='[]')),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='intake.intakeresponse')),
            ],
        ),
    ]
