# Generated by Django 6.0.7 on 2026-07-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeresponse',
            name='class_load',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='deadline_pressure',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='exercise_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='mood_energy',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='intakeresponse',
            name='sleep_consistency',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
