# Generated by Django 5.2.17 on 2026-08-25 15:49

import intake.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_result_archived_at_result_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeresponse',
            name='supporting_file',
            field=models.FileField(blank=True, upload_to='student_uploads/%Y/%m/%d/', validators=[intake.models.validate_supporting_file]),
        ),
    ]
