# Generated by Django 6.0.7 on 2026-08-07 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0002_studentcontactrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcontactrequest',
            name='counselor_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentcontactrequest',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcontactrequest',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replied_contact_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
